export const PayloadID: {
    "0": string;
    "1": string;
    "10": string;
    "11": string;
    "12": string;
    "13": string;
    "14": string;
    "15": string;
    "16": string;
    "17": string;
    "18": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    cancelAllOrdersPayload: number;
    cancelOrderPayload: number;
    depositRequestPayload: number;
    getAccountBalancePayload: number;
    getDepositAddressPayload: number;
    getMovementPayload: number;
    getOrderPayload: number;
    listAccountBalancePayload: number;
    listAccountTransactionsPayload: number;
    listAccountVolumesPayload: number;
    listMovementsPayload: number;
    listOrderPayload: number;
    placeLimitOrderPayload: number;
    placeMarketOrderPayload: number;
    placeStopLimitOrderPayload: number;
    placeStopMarkerOrderPayload: number;
    signMovementPayload: number;
    syncStatePayload: number;
    withdrawRequestPayload: number;
};
export const buyOrder: string;
export function createCancelOrderParams(id: any): any;
export function createDepositRequestParams(address: any, quantity: any): any;
export function createGetAccountBalanceParams(currency: any): any;
export function createGetDepositAddressParams(currency: any): any;
export function createGetMovementParams(id: any): any;
export function createGetOrderparams(id: any): any;
export function createListAccountBalanceParams(ignoreLowBalance: any): any;
export function createListAccountTransactionsParams(cursor: any, fiatSymbol: any, limit: any): any;
export function createListAccountVolumesParams(): any;
export function createListMovementsParams(currency: any, status: any, type: any): any;
export function createListOrdersParams(marketName: any, status: any): any;
export function createPlaceLimitOrderParams(allowTaker: any, amount: any, buyOrSell: any, cancellationPolicy: any, limitPrice: any, marketName: any, cancelAt: any): any;
export function createPlaceMarketOrderParams(amount: any, buyOrSell: any, marketName: any): any;
export function createPlaceStopLimitOrderParams(allowTaker: any, amount: any, buyOrSell: any, cancellationPolicy: any, limitPrice: any, marketName: any, stopPrice: any, cancelAt: any): any;
export function createPlaceStopMarketOrderParams(amount: any, buyOrSell: any, marketName: any, stopPrice: any): any;
export function createSignMovementParams(address: any, amount: any): any;
export function createSyncStateParams(): any;
export function createTimestamp(): any;
export function createWithdrawalRequestParams(address: any, quantity: any): any;
export function decryptSecretKey(encryptionKey: any, cipherText: any, nonce: any, tag: any): any;
export default _default;
export namespace _default {
    function decryptSecretKey(encryptionKey: any, cipherText: any, nonce: any, tag: any): any;
    function deriveHKDFKeysFromPassword(password: any, salt: any): any;
    function encryptSecretKey(encryptionKey: any, secret: any, nonce: any): any;
    function initialize(params: any): any;
    function newMasterSeedFromEntropy(password: any, entropy: any): any;
    function signPayload(config: any, payload: any): any;
}
export function deriveHKDFKeysFromPassword(password: any, salt: any): any;
export function encryptSecretKey(encryptionKey: any, secret: any, nonce: any): any;
export function initialize(params: any): any;
export function newMasterSeedFromEntropy(password: any, entropy: any): any;
export const orderStatusCancelled: string;
export const orderStatusFilled: string;
export const orderStatusOpen: string;
export const orderStatusPending: string;
export const sellOrder: string;
export function signPayload(config: any, payload: any): any;
