version: "2"

plugins:
  tslint:
    enabled: true
    config: tslint.json
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  git-legal:
    enabled: true

exclude_patterns:
  - ".yarn/"
  - "node_modules/"
  - "public/"
  - "sitespeed-results/"
  - ".cache"
  - "k8s"
  - "static"
  - "**/*.d.ts"